### ISSUE TITLE
preview and confirmation for upload

### ISSUE THREAD

**Issue by jpl-hp69** [Kenedy/memorial#1]
Before the data is confirmed it should be displayed for preview (and corrections), with a big button like "now-send-and-have-no-more-chance-to -modify-or-delete".

**Comment by Kenedy** [comment]
@jpl-hp69 Can you check whether it is what you expected? And feel free to modify it if it is not.

**Comment by jpl-hp69** [comment]
Roughly OK. Just - as long as we have no edit/delete - the button should be prevented from accidental confirmation (pressing Enter etc.)
