### ISSUE TITLE
refactoring with ajax

### ISSUE THREAD

**Issue by jpl-hp69** [Kenedy/memorial#13]
When you go back and forth through the menu the application generates a huge list in the browser's history. Nowadays, modern aplications usually do the work in the backgroud.

**Comment by Kenedy** [comment]
It is the other way round. Good SPA (single page applications) insert the entries to the history and implement deep links so it can behave as user expects it - the back button actually returns you to what user perceives as page. I did not structure this as SPA intentionally so we don't have to deal with it. Plus the performance difference here is so little that it shlould not matter.
