### ISSUE TITLE
prepare structure for next years

### ISSUE THREAD

**Issue by jpl-hp69** [Kenedy/memorial#2]
This year's data should remain isolated but still accessible in the next years.
Though the individual years could still have statical pages, I believe it'll be simpler to maintain and allows individuall customization each year,

**Comment by Kenedy** [comment]
Should we just record date and time of form submit? Or let people fill in date when they did the race? Or year?

Once we have some date, we can automatically filter it by date range. What should this range be?

Or should we just manually change the year field every year to have more control over it in case the memorial does not happen on regular bases?

**Comment by jpl-hp69** [comment]
yes -> let people fill in date
yes -> manually change the year field every year
My intention was to run separate events each ears, so that you can register for the current year and you can have a look at the results of previous years. Currently it is only important to have a possibility how to assign the submitted data to "2021".

**Comment by jpl-hp69** [comment]
I hope that next year the race can be held physically on 10.1. in JH.

**Comment by Kenedy** [comment]
- input for date prefilled on current date
- required field
- save this date to result object and show it in the results

**Comment by jpl-hp69** [comment]
Yes, but yet: assign the data to the fixed "race year", i.e. "2021", regardless of the input date.
